In [1]:
import numpy as np

# data type and attributes


In [2]:
#main datatype in numpy is ndarray
a1 = np.array([1,2,3])


In [3]:
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2,3],[6.5,4.3,2.2],[3.9,9.8,2.9]])

In [6]:
a2

array([[1. , 2. , 3. ],
       [6.5, 4.3, 2.2],
       [3.9, 9.8, 2.9]])

In [7]:
type(a2)

numpy.ndarray

In [8]:
a3 = np.array([[[1,2,3],[4,5,6],[6,5,8]],[[11,33,55],[88,99,66],[33,99,55]]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 6,  5,  8]],

       [[11, 33, 55],
        [88, 99, 66],
        [33, 99, 55]]])

In [10]:
type(a3)

numpy.ndarray

In [11]:
a1.shape

(3,)

In [12]:
a2.shape

(3, 3)

In [13]:
a3.shape

(2, 3, 3)

In [14]:
#number of dimension
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [15]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [16]:
a1.size,a2.size,a3.size

(3, 9, 18)

In [17]:
#creatina a dataframe by using numpy
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  6.5  4.3  2.2
2  3.9  9.8  2.9

# creating numpy arrays

In [18]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [19]:
sample_array.dtype

dtype('int32')

In [20]:
 ones = np.ones((2,3))#to know what we can do inside the bracket you can press shift + tab

In [21]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

## note: default value of array is float

In [22]:
ones.dtype

dtype('float64')

In [23]:
type(ones)

numpy.ndarray

In [24]:
zeros = np.zeros((2,4))

In [25]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### arange(): is indicate start, stop and step for example:(startnumber,stop number, step number)

In [26]:
range_array = np.arange(2,14,2)
range_array

array([ 2,  4,  6,  8, 10, 12])

### np.random.randint(lower value, higher value , size=()) : array starts with lower value and ends with higher value arranged randomly in the given size

In [27]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[3, 2, 8, 4, 3],
       [6, 5, 2, 7, 6],
       [0, 9, 3, 5, 8]])

In [28]:
random_array.size

15

In [29]:
random_array.shape

(3, 5)

### The np. random. random() function is used to generate random numbers in the interval of [0.0, 1.0). Note: When representing intervals, square bracket [ means that the number is included in the interval, and round bracket ) means that the number is not included in the interval.

In [30]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.3680919 , 0.62592032, 0.33531907],
       [0.92390858, 0.75248082, 0.30596439],
       [0.20392239, 0.65349025, 0.57739027],
       [0.24755548, 0.33099551, 0.06508113],
       [0.41616271, 0.52429054, 0.41344873]])

In [31]:
random_array_2.shape

(5, 3)

### random.rand(): represent random value in a given size in the float value

In [32]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.63336673, 0.76308264, 0.86405119],
       [0.90274568, 0.70633123, 0.80961493],
       [0.12633305, 0.3977447 , 0.76541625],
       [0.09988618, 0.51200126, 0.88495581],
       [0.77785165, 0.28732406, 0.38634806]])

### random.seed():it refers  the random output to constant for next runs also

In [33]:
np.random.seed(7)
random_array_4 = np.random.random((5,3))
random_array_4

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

# viewing array and matrices

## .unique():With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.
Syntax : np.unique(Array)
Return : Return the unique of an array.

In [34]:
np.unique(random_array_4)

array([0.06593635, 0.07205113, 0.07630829, 0.26843898, 0.2881456 ,
       0.38094113, 0.43840923, 0.4998825 , 0.50112046, 0.53849587,
       0.67923   , 0.72346518, 0.77991879, 0.80373904, 0.97798951])

In [35]:
random_array

array([[3, 2, 8, 4, 3],
       [6, 5, 2, 7, 6],
       [0, 9, 3, 5, 8]])

In [36]:
random_array[0]

array([3, 2, 8, 4, 3])

In [37]:
random_array[2]

array([0, 9, 3, 5, 8])

In [38]:
random_array[:2, :2]

array([[3, 2],
       [6, 5]])

# Manipulating and comparing array

## Arithemetic

In [39]:
array_1 = np.array([[2,4,5],[4,6,7],[8,9,66]])

In [40]:
array_1.shape

(3, 3)

In [41]:
a9 = np.array([[44,66,77],[33,44,1],[9,8,0]])

In [42]:
array_1 + a9

array([[46, 70, 82],
       [37, 50,  8],
       [17, 17, 66]])

In [43]:
array_1 - a9

array([[-42, -62, -72],
       [-29, -38,   6],
       [ -1,   1,  66]])

In [44]:
array_1 * a9

array([[ 88, 264, 385],
       [132, 264,   7],
       [ 72,  72,   0]])

In [45]:
  array_1 / a9

C:\Users\NABZOOR\AppData\Local\Temp\ipykernel_19980\1504522935.py:1: RuntimeWarning: divide by zero encountered in divide
  array_1 / a9


array([[0.04545455, 0.06060606, 0.06493506],
       [0.12121212, 0.13636364, 7.        ],
       [0.88888889, 1.125     ,        inf]])

In [46]:
# floor division removes the decimals (round down)
array_1 // a9

C:\Users\NABZOOR\AppData\Local\Temp\ipykernel_19980\3528315358.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  array_1 // a9


array([[0, 0, 0],
       [0, 0, 7],
       [0, 1, 0]])

In [47]:
array_1 % a9

C:\Users\NABZOOR\AppData\Local\Temp\ipykernel_19980\3854315315.py:1: RuntimeWarning: divide by zero encountered in remainder
  array_1 % a9


array([[2, 4, 5],
       [4, 6, 0],
       [8, 1, 0]])

In [48]:
array_1 ** 2

array([[   4,   16,   25],
       [  16,   36,   49],
       [  64,   81, 4356]])

In [49]:
np.square(array_1)#square() is used to square the element in the array 

array([[   4,   16,   25],
       [  16,   36,   49],
       [  64,   81, 4356]])

In [50]:
np.add(array_1, a9)

array([[46, 70, 82],
       [37, 50,  8],
       [17, 17, 66]])

In [51]:
array_1 % 2

array([[0, 0, 1],
       [0, 0, 1],
       [0, 1, 0]], dtype=int32)

In [52]:
array_1 / 2

array([[ 1. ,  2. ,  2.5],
       [ 2. ,  3. ,  3.5],
       [ 4. ,  4.5, 33. ]])

In [53]:
array_1

array([[ 2,  4,  5],
       [ 4,  6,  7],
       [ 8,  9, 66]])

In [54]:
np.exp(array_1)

array([[7.38905610e+00, 5.45981500e+01, 1.48413159e+02],
       [5.45981500e+01, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 4.60718663e+28]])

In [55]:
np.log(array_1)

array([[0.69314718, 1.38629436, 1.60943791],
       [1.38629436, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 4.18965474]])

# Aggregation:
## Aggregation = performing the same operation on a number of things

In [56]:
listy_list = [1,2,3]
type(listy_list)

list

In [57]:
sum(listy_list)

6

In [58]:
array_1

array([[ 2,  4,  5],
       [ 4,  6,  7],
       [ 8,  9, 66]])

In [59]:
type(array_1)

numpy.ndarray

In [60]:
np.sum(array_1)

111

In [61]:
np.sum(listy_list)

6

## Note: use python methods (sum()) on python datatypes and use Numpy methods on Numpy array(np.sum())

 ### creating a massive numpy array

In [62]:
massive_array = np.random.random(10000)
massive_array.size

10000

In [63]:
massive_array[:100]

array([0.90959353, 0.21338535, 0.45212396, 0.93120602, 0.02489923,
       0.60054892, 0.9501295 , 0.23030288, 0.54848992, 0.90912837,
       0.13316945, 0.52341258, 0.75040986, 0.66901324, 0.46775286,
       0.20484909, 0.49076589, 0.37238469, 0.47740115, 0.36589039,
       0.83791799, 0.76864751, 0.31399468, 0.57262533, 0.27604905,
       0.45284293, 0.35297837, 0.65739946, 0.37035108, 0.45909298,
       0.71932412, 0.41299183, 0.90642327, 0.18045162, 0.74111887,
       0.42237404, 0.42645357, 0.63437987, 0.5229062 , 0.41488598,
       0.00142688, 0.09226235, 0.70939439, 0.5243456 , 0.69616046,
       0.95546832, 0.68291385, 0.05312869, 0.30885268, 0.59259469,
       0.23512041, 0.964971  , 0.94504822, 0.84840088, 0.472324  ,
       0.84147671, 0.13111064, 0.30873366, 0.46299639, 0.7418472 ,
       0.48582523, 0.13687612, 0.34353653, 0.32442617, 0.3004189 ,
       0.1655014 , 0.41490177, 0.44812066, 0.77490038, 0.7963907 ,
       0.52239013, 0.4606303 , 0.7782136 , 0.88728895, 0.67491

In [64]:
%timeit sum(massive_array) #python sum method
%timeit np.sum(massive_array) #numpy sum method

2.06 ms ± 553 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
25.2 µs ± 930 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


#### note: numpy sum method is more faster then the python array

### Mean is average of a given set of data. Let us consider below example  

2
,
 
4
,
 
4
,
 
4
,
 
5
,
 
5
,
 
7
,
 
9
 
2, 4, 4, 4, 5, 5, 7, 9 

These eight data points have the mean (average) of 5: 
2+4+4+4+5+5+7+9/8 = 5

 

In [65]:
np.mean(array_1)

12.333333333333334

In [66]:
np.max(array_1)

66

In [67]:
np.min(array_1)

2

In [68]:
np.std(array_1)

19.084606944399518

### Variance:
    Variance is the sum of squares of differences between all numbers and means. 
Deviation for above example. First, calculate the deviations of each data point from the mean, and square the result of each:

 

In [69]:
# high variance = wider range of numbers
# low variance = lower range of numbers
np.var(array_1)

364.22222222222223

In [70]:
# standard deviation = squareroot of variance
np.sqrt(np.var(array_1))

19.084606944399518

# Reshapping and Transposing

In [71]:
arr_new = np.array([[1,2,3],[4,5,6]])

In [72]:
arr_new

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
arr_new.shape

(2, 3)

In [74]:
arr_new_2 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [75]:
arr_new_2.shape

(2, 3, 3)

In [76]:
arr_new * arr_new_2

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

## NOTE: if you get the above kind of error then we need to reshape the array by using RESHAPING

In [ ]:
arr_new_reshape = arr_new.reshape(2,3,1)# we are adding one in the shape because it is multiplication and its is based on numpy broadcasting rule

In [ ]:
arr_new_reshape.shape

In [ ]:
arr_new_reshape * arr_new_2

### Transpose: interchange the column and row

In [ ]:
a2

In [ ]:
a2.T

## dot product and element product

In [ ]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(5, 3))
mat2 = np.random.randint(10, size=(5,3))

In [ ]:
# Element-wise multiplication (Hadamard product)
mat1 * mat2

## Dot product: first matrix column and second matrix row should be same and size need not to be same . Example: (3x3) . (3 x 2)


In [ ]:
# Dot Product
np.dot(mat1, mat2)

#### for the above error we can use transpose and resolve it 

In [ ]:
# Transpose mat1
mat1.T

In [ ]:
mat1.T.shape, mat2.shape

In [ ]:
mat3 = np.dot(mat1.T, mat2)
mat3

In [ ]:
mat3.shape

## Comparision Operator

In [77]:
a1

array([1, 2, 3])

In [78]:
a2

array([[1. , 2. , 3. ],
       [6.5, 4.3, 2.2],
       [3.9, 9.8, 2.9]])

In [79]:
a1 < a2

array([[False, False, False],
       [ True,  True, False],
       [ True,  True, False]])

In [80]:
bool_array = a1 >= a2
bool_array

array([[ True,  True,  True],
       [False, False,  True],
       [False, False,  True]])

In [81]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [82]:
a1 == a2

array([[ True,  True,  True],
       [False, False, False],
       [False, False, False]])

 ## Sorting Array

In [83]:
random_array_sort = np.random.randint(10, size=(3,5))
random_array_sort

array([[3, 7, 9, 3, 8],
       [1, 5, 6, 5, 5],
       [5, 2, 2, 6, 1]])

In [84]:
random_array_sort.shape

(3, 5)

In [85]:
np.sort(random_array_sort)

array([[3, 3, 7, 8, 9],
       [1, 5, 5, 5, 6],
       [1, 2, 2, 5, 6]])

## np.argsort(): sorted the array and give the indices values of the given array in sorted form

In [88]:
random_array_sort

array([[3, 7, 9, 3, 8],
       [1, 5, 6, 5, 5],
       [5, 2, 2, 6, 1]])

In [86]:
np.argsort(random_array_sort)

array([[0, 3, 1, 4, 2],
       [0, 1, 3, 4, 2],
       [4, 1, 2, 0, 3]], dtype=int64)

In [89]:
a1

array([1, 2, 3])

In [90]:
np.argmin(a1)

0

In [91]:
np.argmax(a1)

2

In [93]:
random_array_sort

array([[3, 7, 9, 3, 8],
       [1, 5, 6, 5, 5],
       [5, 2, 2, 6, 1]])

In [96]:
np.argmax(random_array_sort)

2

In [98]:
np.argmax(random_array_sort, axis=0) # it checks the maximum number vertically(axis = 0) and return their indices

array([2, 0, 0, 2, 0], dtype=int64)

In [99]:
np.argmax(random_array_sort, axis = 1)# it checks the maximum number horizontally (axis = 1)and return their indices

array([2, 2, 3], dtype=int64)

## Turn image into numpy array

# lets check the image from the folder
<img src="images/shonu.png"/>

In [100]:
from matplotlib.image import imread
shonu = imread("images/shonu.jpg")
print(type(shonu))

<class 'numpy.ndarray'>


In [105]:
shonu.size, shonu.shape, shonu.ndim

(5760000, (1600, 1200, 3), 3)

In [107]:
shonu

array([[[ 57,  65,  52],
        [ 59,  67,  56],
        [ 62,  68,  58],
        ...,
        [171, 189, 189],
        [173, 191, 191],
        [174, 192, 192]],

       [[ 62,  67,  44],
        [ 66,  69,  48],
        [ 70,  73,  52],
        ...,
        [171, 189, 189],
        [173, 191, 191],
        [174, 192, 192]],

       [[ 89,  89,  51],
        [ 91,  91,  53],
        [ 96,  94,  56],
        ...,
        [171, 189, 189],
        [173, 191, 191],
        [174, 192, 192]],

       ...,

       [[141, 139, 124],
        [141, 139, 124],
        [142, 140, 125],
        ...,
        [166, 149, 157],
        [169, 157, 157],
        [170, 162, 159]],

       [[137, 135, 120],
        [138, 136, 121],
        [139, 137, 122],
        ...,
        [177, 165, 165],
        [178, 174, 163],
        [176, 177, 161]],

       [[135, 133, 118],
        [136, 134, 119],
        [137, 135, 120],
        ...,
        [183, 174, 169],
        [181, 182, 166],
        [179, 184, 161]]